# Generated by Django 5.2.6 on 2025-09-10 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date Cleaned')),
                ('cleaning_methods', models.CharField(choices=[('HAND', 'Hand Wash (Soap & Water)'), ('WIPES', 'Sneaker Wipes / Magic Eraser'), ('MACHINE', 'Machine Wash'), ('DRY', 'Dry Brush'), ('KIT', 'Sneaker Cleaning Kit'), ('STEAM', 'Steam Cleaning'), ('SOLE', 'Sole Whitening'), ('SUEDE', 'Suede/Nubuck Care'), ('LEATHER', 'Leather Care'), ('PRO', 'Professional Service')], default='HAND', max_length=7)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.shoe')),
            ],
        ),
    ]
