# Generated by Django 5.2.6 on 2025-09-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_closet_alter_cleaning_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='closets',
            field=models.ManyToManyField(to='main_app.closet'),
        ),
    ]
